"use strict";
// Уровень автоматически находится загрузчиком по имени файла level6.js.
GameApp.levels.level6 = {
  ...GameApp.levels.level1,
  id: "level6",
  order: 6,
  name: "Они уже здесь",
  reward: 200,
  waves: [
    { type: "runner3", count: 1, delay: 2, side: "left", storm: true },
    { type: "runner2", count: 3, delay: 5, side: "left", storm: false },
    { type: "ninja", count: 4, delay: 5, side: "left", storm: false },
    { type: "brute", count: 1, delay: 7, side: "right", storm: true },
    { type: "brute", count: 2, delay: 2, side: "left", storm: true },
    { type: "runner", count: 5, delay: 5, side: "right", storm: false },
    { type: "runner", count: 5, delay: 4, side: "left", storm: false },
    { type: "runner2", count: 1, delay: 6, side: "left", storm: true },
    { type: "runner3", count: 1, delay: 2, side: "left", storm: false },
    { type: "runner2", count: 1, delay: 1.5, side: "left", storm: false },
    { type: "sniper", count: 6, delay: 8, side: "left", storm: false },
    { type: "splitter", count: 1, delay: 5, side: "right", storm: false },
    { type: "brute", count: 1, delay: 9, side: "right", storm: false },
    { type: "runner", count: 12, delay: 0, side: "left", storm: false },
    { type: "runner2", count: 2, delay: 2, side: "left", storm: false },
    { type: "brute", count: 2, delay: 7, side: "right", storm: true },
    { type: "brute", count: 1, delay: 0, side: "left", storm: true },
    { type: "runner", count: 7, delay: 11, side: "left", storm: false },
    { type: "runner", count: 2, delay: 0.3, side: "left", storm: false },
    { type: "runner", count: 2, delay: 0.3, side: "left", storm: false },
    { type: "runner", count: 2, delay: 0.3, side: "left", storm: false },
    { type: "runner", count: 2, delay: 0.3, side: "left", storm: false },
    { type: "runner", count: 2, delay: 0.3, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.2, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.1, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.1, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.1, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.1, side: "left", storm: false },
    { type: "runner", count: 1, delay: 0.1, side: "left", storm: false },
    { type: "runner2", count: 5, delay: 2, side: "left", storm: false },
  ]
};
